[project]
name = "serve-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.121.3",
    "flytekit>=1.16.9",
    "ray[serve,serve-grpc]>=2.52.0",
    "ultralytics>=8.3.231",
]
